# Generated by Django 5.1.1 on 2024-10-02 03:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_productentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productentry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productentry',
            name='is_avail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productentry',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
