# Generated by Django 5.1.1 on 2024-10-07 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productentry_date_productentry_is_avail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productentry',
            old_name='name',
            new_name='product',
        ),
    ]
