# Generated by Django 5.1.1 on 2024-10-08 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_name_productentry_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productentry',
            old_name='is_avail',
            new_name='available',
        ),
    ]
