# Generated by Django 5.1.1 on 2024-10-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_is_avail_productentry_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productentry',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
